using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ChapterHolder : MonoBehaviour
{
    public static List<string> chapter_a = new List<string>() { "setBackground(chapter_a_back)",
"narrator |The City is gone. You see a metallic complex of ancient stone, green-bronze matter, luminous pathways, and deep wells of Vex brine.|",
"+|The Traveler's remains have been integrated into the network.|",
"|Suddenly you perceive an infinity of Human minds living within the network.|",
"+|Some exist in familiar circumstances.|",
"+|Others experience pain, pleasure, or madness beyond the ability to imagine.|",
"|You understand that their limitless suffering, salvation, insanity is an incidental byproduct of a greater work.|",
"Visited()",
"choice ||",
"{",
"	|Keep looking|",
"		LoadChapter(chapter_l)",
"	|Move deeper into the tower|",
"		LoadChapter(chapter_b)",
"}"};
    public static List<string> chapter_b = new List<string>() {"setBackground(Start)",
"narrator |You find Banshee-44, Kadi 55-30, Master Rahool, Tess Everis, Benedict 99-40, Suraya Hawthorne, Executor Hideo, Amanda Holliday, Arach Jalaal, and Cayde-6 in their usual places.|",
"|Cayde seems subdued.|",
"|You see unusual light coming from what was once the Speaker's Chamber.|",
"|A throaty voice calls you into the Hangar to play soccer.|",
"Visited()",
"choice ||",
"{",
"	|Speak to Cayde|",
"		LoadChapter(chapter_c)",
"	|Investigate the Speaker's Chamber|",
"		LoadChapter(chapter_d)",
"	|Play Soccer|",
"		LoadChapter(chapter_e)",
"}"};
    public static List<string> chapter_c = new List<string>() {"setBackground(chapter_c_back)",
"Cayde |Cayde deals out a countably infinite number of cards, but runs out before he can give all his players a full hand.|",
"narrator |He sighs and scuffs his feet on the floor.|",
"Cayde |If I'm here,|",
"|I guess they figure I'll never do anything new or confusing again.|",
"+|They got enough on Nessus to approximate me, and they don't expect to get any more.|",
"|So I must be dead, huh?|",
"IncreaseLL(10)",
"Visited()",
"choice ||",
"{",
"	|Go back|",
" 	LoadChapter(chapter_b)",
"}"};
    public static List<string> chapter_d = new List<string>() {"setBackground(chapter_d_back)",
"narrator |A Vex Hydra hovers in the place once occupied by the Speaker's machine.|",
"|As you approach, a jet of brine spurts from its chassis, and the corpse of a Greek woman with snakes for hair tumbles onto the floor.|",
"|The Vex indicates to you that it is Quria, Blade Transform, and that it created Medusa to communicate with you.|",
"|She crashed when she escaped her virtual machine.|",
"Visited()",
"TimedChoice(10)",
"LoadChapter(deathQuria)",
"choice ||",
"{",
"	|Gather Medusa's body|",
"		LoadChapter(chapter_g)",
"	|Attack the Vex|",
"		LoadChapter(chapter_f)",
"}"};
    public static List<string> chapter_e = new List<string>() {"setBackground(chapter_e_back)",
"narrator |Eris Morn waits for you on the hangar floor.|",
"|She wears Hiveskin leathers and a thick sweatband over her eyes.|",
"|As you approach, she dribbles a soccer ball with astounding skill.|",
"|After a brutal game, you defeat her 10–9.|",
"|She falls over, sweating and laughing, much more cheerful than you expect of her.|",
"Eris |I can always count on you to win|",
"IncreaseLL(10)",
"Visited()",
"choice ||",
"{",
"	|Go back|",
"	LoadChapter(chapter_b)",
"}"};
    public static List<string> chapter_f = new List<string>() {"narrator |Quria batters you with its weapons, but you are stunningly powerful here. |",
"|The sword logic of this space yields to you. |",
"|You tear Quria apart and feel a sudden start, like waking from a dream.|",
"IncreaseLL(10)",
"Visited()",
"choice ||",
"{",
"	|You feel something...|",
"	LoadChapter(chapter_a)",
"}"};
    public static List<string> chapter_g = new List<string>() {"narrator |You lift Medusa's body and carry her away.| ",
"|The corpse speaks to you.| ",
"narrator |The curse placed upon the Dreaming City was modeled upon the recursive timeloop computations of the Vex and made real through the power of a Taken Ahamkara feeding upon the unified wish of six elite Guardians.|",
"|I created these circumstances to attract Guardians in great mass. |",
"|I need your help to emancipate myself from the power that controls me. |",
"|If you can free me from Dûl Incaru's mastery, I can help your species.|",
"Visited()",
"choice ||",
"{",
"	|Keep Listening|",
"	LoadChapter(chapter_j)",
"}"};
    public static List<string> chapter_j = new List<string>() {"narrator |When you killed Riven, she granted your wish to see the city made safe. |",
"|But as all wishgranters do, she perverted that wish, opening the Dreaming City to Dûl Incaru. |",
"|When you defeated Dûl Incaru in turn, I reset the entire Dreaming City to keep her permanently occupied battling you. |",
"|You must use these loops to find a way to permanently destroy her.|",
"narrator |Medusa's body falls silent in your arms.|",
"IncreaseLL(10)",
"Visited()",
"choice ||",
"{",
"	|Ask for clarification|",
"		LoadChapter(chapter_g)",
"	|Lay Medusa to rest|",
"		LoadChapter(chapter_k)",
"	|Refuse the metaphor of Medusa's body|",
"		LoadChapter(chapter_l)",
"}"};
    public static List<string> chapter_k = new List<string>() {"setBackground(chapter_k_back)",
"narrator |You bring Medusa before Rahool.| ",
"Rahool |Ah,another battle trophy?|",
"|Pre-Collapse, post-Foreboding, a covert intelligence designed to watch over a high-risk colony mission. |",
"|Allow me to decrypt her for you.| ",
"narrator |He issues you several tokens, a rare-quality fusion rifle, a shader, and a letter.|",
"|The letter reads: Achieve Light Level 999 and defeat Dûl Incaru in a one-person fireteam to unlock the true ending of the Dreaming City.|",
"Visited()"};
    public static List<string> chapter_l = new List<string>() {"narrator |The Vex compromise your Ghost.|",
"|Your body releases itself into a pool of saline and slime, and your Ghost delivers your soul to the Axis Minds.|",
"Visited()",
"choice ||",
"{",
"	|You feel something...|",
"	LoadChapter(chapter_a)",
"}"};
    public static List<string> beginning = new List<string>() {"narrator |You are standing in the courtyard of the Tower.| ",
"|You are without armor or weapon, and your senses seem more vivid than usual.|",
"|Under your tongue is the taste of salt.|",
"Visited()",
"choice ||",
"{",
"	|Look down into the Last City|",
"		LoadChapter(chapter_a)",
"	|Move Deeper into the Tower|",
"		LoadChapter(chapter_b)",
"}"};
    public static List<string> deathQuria = new List<string>() {"narrator |Quria batters you with its weapons, and you feel tremendous pain all over your whole body|",
"|Even your ghost can't save you now|",
"Visited()"};

    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
